from enum import StrEnum


class RunState(StrEnum):
    CREATED = "CREATED"
    RESOLVING = "RESOLVING"
    PLANNING = "PLANNING"
    EXECUTING = "EXECUTING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    RECONCILING = "RECONCILING"
    BLOCKED_NEEDS_HUMAN = "BLOCKED_NEEDS_HUMAN"
    DEFERRED = "DEFERRED"
    CANCELED = "CANCELED"
    COMPLETED_VERIFIED = "COMPLETED_VERIFIED"
    COMPLETED_NO_ACTION_REQUIRED = "COMPLETED_NO_ACTION_REQUIRED"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"


class ActionState(StrEnum):
    PROPOSED = "PROPOSED"
    POLICY_CHECKED = "POLICY_CHECKED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVED = "APPROVED"
    PREPARED = "PREPARED"
    EXECUTING = "EXECUTING"
    UNKNOWN = "UNKNOWN"
    RECONCILING = "RECONCILING"
    RETRYABLE = "RETRYABLE"  # means explicitly SAFE_TO_RETRY after reconciliation policy
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"  # terminal failure; never retried
    CANCELED = "CANCELED"
    INVALIDATED = "INVALIDATED"


class RiskLevel(StrEnum):
    READ = "READ"
    INTERNAL_WRITE = "INTERNAL_WRITE"
    EXTERNAL_WRITE = "EXTERNAL_WRITE"
    DESTRUCTIVE = "DESTRUCTIVE"


class EmailIntent(StrEnum):
    NONE = "NONE"
    ACCEPTED = "ACCEPTED"
    DECLINED = "DECLINED"
    DELAY = "DELAY"
    DO_NOT_CONTACT = "DO_NOT_CONTACT"
    AMBIGUOUS = "AMBIGUOUS"


class RenewalStatus(StrEnum):
    PENDING = "PENDING"
    RENEWED = "RENEWED"
    DECLINED = "DECLINED"
    CANCELED = "CANCELED"
    EXPIRED = "EXPIRED"
    DEFERRED = "DEFERRED"
    UNKNOWN = "UNKNOWN"


class ApprovalStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CLAIMED = "CLAIMED"
    CONSUMED = "CONSUMED"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"
